# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Infectious Disease Epidemiology for the Anthroposcene (IDEA) Lab"
title_separator: "-"
subtitle: "Bridging data, disciplines, and decision-making to detect, anticipate, and respond to epidemic and pandemic threats in a destabilised world."
name: "Dr Charlotte Hammer"
description: "Infectious Disease Epidemiology for the Anthroposcene Lab"
url: "https://hammercc.github.io"
baseurl: ""
logo: "/assets/images/icon.jpg"
masthead_title: ""
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: false
copyright: ""
copyright_url: ""

# Navigation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      nav_exclude: true

navigation:
  - title: "Team"
    url: "/team/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Contact"
    url: "/contact/"

# Social Sharing
social:
  type: Person
  name: "Dr Charlotte Hammer"
  links:
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8288-0288"
    - label: "BlueSky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://blueskyweb.xyz/yourprofile"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"

# Analytics
analytics:
  provider: false

# Site Author
author:
  name: "Dr Charlotte Hammer"
  avatar: "/assets/images/charlotte.jpg"
  bio: ""
  location: "University of Cambridge"
  email: "ch950@cam.ac.uk"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ch950@cam.ac.uk"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hammercc.github.io"

# Footer
footer:
  content: "© 2025 IDEA Lab"
  links:
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8288-0288"
    - label: "BlueSky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://blueskyweb.xyz/yourprofile"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
  since: "2013"

# Include / Exclude
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone:

# Pagination
paginate: 5
pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
